#!/usr/bin/env ruby
require File.expand_path('../config/boot', __FILE__)

rack_pid = spawn(File.join(APP_ROOT, 'bin', 'webserver'))
worker_pid = spawn(File.join(APP_ROOT, 'bin', 'worker'))

if not (ARGV.first == '-n' || ARGV.first == '--no-launch')
  require 'launchy'
  sleep 2; Launchy.open("http://localhost:8080/")
end

Process.waitall

puts '=> Done'.green.bold
